
import React from 'react';
import { Category, ExpenseItem, Language } from './types';

export const CATEGORY_COLORS: Record<string, string> = {
  [Category.Savings]: '#10b981',      // Emerald-500
  [Category.EmergencyFund]: '#f59e0b', // Amber-500
  [Category.Investment]: '#6366f1',    // Indigo-500
  [Category.DailyExpenses]: '#ef4444', // Red-500
  [Category.Lifestyle]: '#ec4899',     // Pink-500
};

export const getCategoryColor = (category: string) => {
  return CATEGORY_COLORS[category] || '#94a3b8'; // Slate-400 for custom categories
};

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    income: "Income Sources",
    inflows: "Monthly Inflows",
    mainSalary: "Main Salary",
    bonus: "Bonus",
    thr: "Holiday Allowance (THR)",
    freelance: "Freelance",
    wealth: "Wealth & Assets",
    wealthDesc: "Track your bank accounts and total net worth.",
    totalValue: "Total Value",
    addAsset: "Add Asset",
    editAsset: "Edit Asset",
    accountName: "Account Name",
    balance: "Balance",
    confirmAsset: "Confirm Asset",
    allocations: "Monthly Allocations",
    routineItems: "Routine items sync across periods.",
    newEntry: "New Entry",
    editAllocation: "Edit Allocation",
    addAllocation: "Add New Allocation",
    routineDesc: "Routine items reappear every month. Temporary items are for one-time use.",
    routine: "Routine",
    temporary: "Temporary",
    oneTime: "One-time",
    itemName: "Item Name",
    amount: "Amount",
    category: "Category",
    customCategory: "Custom Category",
    note: "Note",
    save: "Save Allocation",
    update: "Update Allocation",
    paid: "Paid",
    item: "Item",
    type: "Type",
    actions: "Actions",
    noEntries: "No entries for this period.",
    noAssets: "No assets registered yet.",
    availableBalance: "Available Balance",
    expenses: "Expenses",
    saveChanges: "Save Changes",
    resetApp: "Reset App",
    analysis: "Expert AI Insights",
    analysisSub: "Strategic Wealth Planning",
    analysisDesc: "Click below to generate a comprehensive strategy based on your current data.",
    analyzeBtn: "Analyze My Finances",
    viewAnalysis: "View Analysis",
    refreshAnalysis: "Refresh Data & Re-analyze",
    strategyTitle: "Financial Strategy Audit",
    auditFor: "Analysis for",
    closeAudit: "Close Audit",
    reRunAudit: "Re-Run Analysis",
    spendingMix: "Fixed vs Discretionary Mix",
    survivalBaseline: "Routine costs are your \"Survival Baseline\"",
    routineFixed: "Routine (Fixed)",
    discretionary: "Discretionary",
    remaining: "Remaining Balance",
    fixedMonthly: "Fixed monthly obligations",
    variableSpending: "Variable/One-time spending",
    freeCashFlow: "Free Cash Flow",
    unallocated: "Unallocated funds",
    budgetDeficit: "Budget deficit",
    savingsGoal: "Savings goal",
    noEmergency: "No allocation for Emergency Fund.",
    resetConfirm: "Clear ALL locally saved data?",
    globalRoutineActive: "Global Routine Synchronization Active.",
    compareWithPrev: "Compare with Previous Month",
    exitComparison: "Exit Comparison View",
    comparisonTitle: "Monthly Delta Analysis",
    comparisonDesc: "Tracking changes in spending patterns compared to the previous recorded period.",
    added: "Added",
    removed: "Removed",
    modified: "Changed",
    noChanges: "No changes detected between these periods.",
    delta: "Delta"
  },
  id: {
    income: "Sumber Pendapatan",
    inflows: "Pemasukan Bulanan",
    mainSalary: "Gaji Pokok",
    bonus: "Bonus",
    thr: "THR",
    freelance: "Freelance / Sampingan",
    wealth: "Kekayaan & Aset",
    wealthDesc: "Pantau rekening bank dan total kekayaan bersih Anda.",
    totalValue: "Total Nilai",
    addAsset: "Tambah Aset",
    editAsset: "Edit Aset",
    accountName: "Nama Akun",
    balance: "Saldo",
    confirmAsset: "Konfirmasi Aset",
    allocations: "Alokasi Bulanan",
    routineItems: "Item rutin sinkron di setiap periode.",
    newEntry: "Entri Baru",
    editAllocation: "Edit Alokasi",
    addAllocation: "Tambah Alokasi Baru",
    routineDesc: "Item rutin muncul setiap bulan. Item sementara untuk sekali pakai.",
    routine: "Rutin",
    temporary: "Sementara",
    oneTime: "Sekali Pakai",
    itemName: "Nama Item",
    amount: "Jumlah",
    category: "Kategori",
    customCategory: "Kategori Kustom",
    note: "Catatan",
    save: "Simpan Alokasi",
    update: "Update Alokasi",
    paid: "Lunas",
    item: "Item",
    type: "Tipe",
    actions: "Aksi",
    noEntries: "Belum ada entri untuk periode ini.",
    noAssets: "Belum ada aset terdaftar.",
    availableBalance: "Saldo Tersedia",
    expenses: "Pengeluaran",
    saveChanges: "Simpan Perubahan",
    resetApp: "Reset Aplikasi",
    analysis: "Wawasan Pakar AI",
    analysisSub: "Perencanaan Kekayaan Strategis",
    analysisDesc: "Klik di bawah untuk membuat strategi komprehensif berdasarkan data Anda.",
    analyzeBtn: "Analisis Keuangan Saya",
    viewAnalysis: "Lihat Analisis",
    refreshAnalysis: "Segarkan Data & Analisis Ulang",
    strategyTitle: "Audit Strategi Keuangan",
    auditFor: "Analisis untuk",
    closeAudit: "Tutup Audit",
    reRunAudit: "Jalankan Ulang Analisis",
    spendingMix: "Bauran Tetap vs Diskresioner",
    survivalBaseline: "Biaya rutin adalah \"Survival Baseline\" Anda",
    routineFixed: "Rutin (Tetap)",
    discretionary: "Diskresioner",
    remaining: "Sisa Saldo",
    fixedMonthly: "Kewajiban bulanan tetap",
    variableSpending: "Pengeluaran variabel/sekali-kali",
    freeCashFlow: "Arus Kas Bebas",
    unallocated: "Dana belum teralokasi",
    budgetDeficit: "Defisit anggaran",
    savingsGoal: "Target tabungan",
    noEmergency: "Belum ada alokasi untuk Dana Darurat.",
    resetConfirm: "Hapus SEMUA data yang tersimpan secara lokal?",
    globalRoutineActive: "Sinkronisasi Rutin Global Aktif.",
    compareWithPrev: "Bandingkan dengan Bulan Lalu",
    exitComparison: "Keluar dari Tampilan Perbandingan",
    comparisonTitle: "Analisis Delta Bulanan",
    comparisonDesc: "Melacak perubahan pola pengeluaran dibandingkan dengan periode tercatat sebelumnya.",
    added: "Ditambahkan",
    removed: "Dihapus",
    modified: "Berubah",
    noChanges: "Tidak ada perubahan terdeteksi di antara periode ini.",
    delta: "Selisih"
  }
};

export const INITIAL_EXPENSES: ExpenseItem[] = [];
